# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 05:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the article.', max_length=1000)),
                ('publication_date', models.DateField(default=datetime.date.today, help_text='Date when this article will be public')),
                ('hero', models.ImageField(upload_to='hero/')),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='extra/')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(help_text='Author of the article.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('is_public', models.BooleanField(default=True, help_text='Tick, if the category is public.')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_category', to='article.Category'),
        ),
    ]
